language: rust
sudo: required # required for some configurations
# tarpaulin has only been tested on bionic and trusty other distros may have issues
dist: bionic
addons:
    apt:
        packages:
            - libssl-dev
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_script: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # Get coverage report and upload it for codecov.io.
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi